<a href="https://colab.research.google.com/github/hannahchaganti99/HDS5210_InClassHannah/blob/master/Copy_of_module31_query_sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PandaSQL

In [5]:
%%bash
pip install pandasql

Requirement already satisfied: pandasql in /usr/local/lib/python3.10/dist-packages (0.7.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from pandasql) (1.26.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.10/dist-packages (from pandasql) (2.0.36)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2024.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy->pandasql) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy->pandasql) (3.1.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.16.0)

In [6]:
import pandas as pd
import pandasql as ps

In [7]:
data = pd.read_csv('complications.csv')

In [8]:
data.head()

,provider_id,hospital_name,address,city,state,zip_code,county_name,phone_number,measure_id,measure_name,compared_to_national,denominator,score,lower_estimate,higher_estimate,footnote,measure_start_date,measure_end_date
0,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,COMP_HIP_KNEE,Rate of complications for hip/knee replacement...,No Different Than the National Rate,292,3.2,2.1,4.8,NaN,2015-04-01T00:00:00.000,2018-03-31T00:00:00.000
1,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_AMI,Death rate for heart attack patients,No Different Than the National Rate,688,13,11.0,15.5,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
2,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_CABG,Death rate for CABG surgery patients,No Different Than the National Rate,291,4.3,2.6,6.8,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
3,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_COPD,Death rate for COPD patients,No Different Than the National Rate,411,8.8,6.7,11.4,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
4,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_HF,Death rate for heart failure patients,No Different Than the National Rate,869,12.7,10.7,15.0,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000

In [9]:
sql = """
select city, count(distinct [provider_id]) as providers
from data
group by city
order by providers desc
"""

In [10]:
cities = ps.sqldf(sql, locals())

In [11]:
cities

              city  providers
0       BIRMINGHAM          4
1       MONTGOMERY          2
2           MOBILE          2
3          GADSDEN          2
4           DOTHAN          2
5         ANNISTON          2
6         WINFIELD          1
7         WETUMPKA          1
8       TUSCALOOSA          1
9        TALLASSEE          1
10       TALLADEGA          1
11       SHEFFIELD          1
12      SCOTTSBORO          1
13           OZARK          1
14             OPP          1
15         OPELIKA          1
16         MOULTON          1
17         LUVERNE          1
18          JASPER          1
19      HUNTSVILLE          1
20        HAMILTON          1
21      GROVE HILL          1
22      GREENSBORO          1
23          GENEVA          1
24      FORT PAYNE          1
25           FOLEY          1
26        FLORENCE          1
27         FAYETTE          1
28        FAIRHOPE          1
29           EUTAW          1
30         EUFAULA          1
31      ENTERPRISE          1
32         DECATUR          1
33       DADEVILLE          1
34         CULLMAN          1
35     CENTREVILLE          1
36          CENTRE          1
37          CAMDEN          1
38         BREWTON          1
39            BOAZ          1
40          ATHENS          1
41         ASHLAND          1
42       ANDALUSIA          1
43  ALEXANDER CITY          1
44       ALABASTER          1

In [12]:
data[data['county_name']=='JEFFERSON'].groupby(['city','provider_id']).count().groupby(['city'])['hospital_name'].count()

city
BIRMINGHAM    4
Name: hospital_name, dtype: int64